INJURY_RISK_HIGH = "INJURY_RISK_HIGH"
INJURY_RISK_CRITICAL = "INJURY_RISK_CRITICAL"
ACWR_ALERT = "ACWR_ALERT"
TALENT_SIGNAL = "TALENT_SIGNAL"
GRANT_DEADLINE = "GRANT_DEADLINE"
CASHFLOW_DEFICIT = "CASHFLOW_DEFICIT"
SESSION_REMINDER = "SESSION_REMINDER"
WEEKLY_PERFORMANCE_DIGEST = "WEEKLY_PERFORMANCE_DIGEST"
MILESTONE_ACHIEVED = "MILESTONE_ACHIEVED"

DEFAULT_CHANNELS = {
    "in_app_enabled": True,
    "email_enabled": True,
    "push_enabled": False,
}
